### ISSUE TITLE
Latest Logger overflow bug

### ISSUE THREAD

**Issue by griseraner** [crymp-net/client-server#89]
This happens on server,  since I added newest Logger

How to trigger: Enable !adminconsole and !kick myself
I've seen similar issue in client, with localized label @label@label@label etc, maybe same issue?

Added a `CryLogAlways("Server::Print %s", inszText);` and it logs this:

> Server::Print [net 12:05:54.854] Disconnect DESKTOP-IGQAA4K.lan:52448; profid=0; cause=5; msg='test'
> Server::Print Server::Print [net 12:05:54.854] Disconnect DESKTOP-IGQAA4K.lan:52448; profid=0; cause=5; msg='test'
> Server::Print Server::Print Server::Print [net 12:05:54.854] Disconnect DESKTOP-IGQAA4K.lan:52448; profid=0; cause=5; msg='test'
> Server::Print Server::Print Server::Print Server::Print [net 12:05:54.854] Disconnect DESKTOP-IGQAA4K.lan:52448; profid=0; cause=5; msg='test'
> Server::Print Server::Print Server::Print Server::Print Server::Print [net 12:05:54.854] Disconnect DESKTOP-IGQAA4K.lan:52448; profid=0; cause=5; msg='test'

**Comment by ccomrade** [comment]
This is expected behavior. `Server::Print` is called always when something is written to console. `CryLogAlways` writes a message to both console and log file. That means adding `CryLogAlways` into `Server::Print` creates an endless loop, because when `CryLogAlways` is called, it does console write and triggers `Server::Print`, which calls `CryLogAlways` again.
